name: Build and Deploy
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: nuagedelait/course-handoff@master
      env:
        ACCESS_TOKEN: ${{ secrets.CI_TOKEN }}
        TARGET_REPO: nuagedelait/course-handoff
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: src/.vuepress/dist/
        COMMIT_MESSAGE: 'Auto deploy from Github Actions'
